### ISSUE TITLE
optymalizacja kodu

### ISSUE THREAD

**Issue by pgrycz** [pgrycz/hello-exercises#2]
znalazłem rozwiązanie w PHP na zarządzanie rozdzielonym kodem html (header, różna zawartość, footer)

" index.php:

<?php
include('header.html');
if(file_exists(htmlspecialchars($_GET['p']).'.html')){
include(htmlspecialchars($_GET['p']).'.html');
}else echo 'Wybrana podstrona nie istnieje!';
include('footer.html');
?>

- header.html
- footer.html
- strona1.html
- strona2.html
i wpisując strona.pl/?p=strona1 otworzy header, strona2 i footer "

czy można to osiągnąć inną metodą, czy ta powyższa jest optymalna ?

albo np:
<?php include ('header.php'); ?>
           HTML content 
<?php include ('footer.php'); ?>

czy header (tu jego rolę pełni navbar) ma zawierać meta tagi oraz scieżki stylów?

**Comment by pgrycz** [comment]
albo i tak:
```<?php include 'header.php'; ?>
<!-- HTML content  -->
<?php include 'footer.php'; ?>```

**Comment by rkrysinski** [comment]
Jeśli chodzi o javascriptowe rozwiązania to można też skorzystać z:
- underscorejs -> template feature -> http://underscorejs.org/#template
- AngularJS

Jeśli chcesz skupić się na javascriptowej technologi to pewnie underscore na początek byłby łatwiejszy. Przejście później na angular'a będzie łatwiejsze.
