### ISSUE TITLE
przejście na projekt nodejs + bower

### ISSUE THREAD

**Issue by rkrysinski** [pgrycz/hello-exercises#3]
Żeby wprowadzić porządek w projekcie, warty skorzystać z nodejs na topi którego można zainstalować bower'a

**Comment by pgrycz** [comment]
ok, to ten temat u mnie do przyswojenia (nodejs i bower) od podstaw

**Comment by rkrysinski** [comment]
ticket przypisałem do siebie, żebyś mógł popatrzeć jak to wygląda.
Poczytaj sobie o tym, popatrz i pobaw sie tym i daj znać jak coś będzie nie
jasne

On Fri, Jul 31, 2015 at 6:43 PM, pgrycz <notifications@github.com> wrote:

> ok, to ten temat u mnie do przyswojenia (nodejs i bower) od podstaw
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
Roman

Nothing is impossible; impossible itself says "I m possible"...

**Comment by pgrycz** [comment]
tzn, jakiś link?
