### ISSUE TITLE
Add underscore library to the project.

### ISSUE THREAD

**Issue by rkrysinski** [pgrycz/hello-exercises#6]
Update bower.json with "underscore" : "1.7.0", in dependencies section and see what happens in app/libs directory. 

bower.json file after update should looks like:
{
  "name": "hello-exercises",
  "description": "Front-End example",
  "version": "0.0.1",
  "license": "Proprietary software",
  "private": true,
  "dependencies": {
    "jquery": "2.0.3",
    "underscore" : "1.7.0",
    "bootstrap": "3.3.5"
  }
}

**Comment by pgrycz** [comment]
updated bower.json registry => 'underscore' dependencies installed in custom dir set in .bowerrc
