### ISSUE TITLE
Make a decision about technology stack

### ISSUE THREAD

**Issue by rkrysinski** [pgrycz/hello-exercises#7]
Do you have any preferences which framework/technology stack to choose?

**Comment by pgrycz** [comment]
Not yet or, honestly in this moment of my knowledge, not sure what technology would be optimal (fit the future project needs).
As I have some experience with javascript environment, general preference is a modern js framework, especially with it's tendency to growing popularity => react, polymer, angular x.x, etc...but don't know about each practical pros and cons.

**Comment by rkrysinski** [comment]
OK, so let's focus on AngularJS. Please go through some basic tutorials available on the web, and come back to this topic.

**Comment by pgrycz** [comment]
Think I'm initially ready, found this:
http://angular-ui.github.io/bootstrap/#/top
Can I use this library to rewrite the justified-nav example?

**Comment by rkrysinski** [comment]
Yes, please use this library.
